### ISSUE TITLE
Automatically generated route methods should include a route that GETs a specific item by id

### ISSUE THREAD

**Issue by MahmoudThePeltist** [Mahamed-Belkheir/haykal#4]
![image](https://user-images.githubusercontent.com/35870737/109703708-7309bf80-7b9e-11eb-80ef-b7a483946f34.png)

**Comment by MahmoudThePeltist** [comment]
I know that in the backend the read method accepts a query param object, for example `{id: 1}` but what I mean is, that since this is a default REST endpoint, it should be automatically generated. thx x x o o

**Comment by Mahamed-Belkheir** [comment]
This requires assuming the resource has an id, or a singular, primary id. so providing this out of the box would be restrictive.
How ever, v0.2 will have a reusable and editable resource router and use case class, editing or extending those to support an id route would be a simple endeavor.
